### ISSUE TITLE
Ability to show points rather than lines

### ISSUE THREAD

**Issue by willjobs** [zdila/gpx-animator#314] opened 2021-01-26 06:00 UTC
Would it be possible to add an option so that we see the dots (markers) instead of connected lines? The use case is that I'm combining many individual runs into a single GPX file, all in one track, and I don't want to have a line jumping from one part of the map to the next. I'd rather show dots (with some opacity/transparency) that are unconnected.

**Comment by McPringle** [comment] 2021-01-26 10:21
Hi @willjobs, just to understand your use case: Why do you merge multiple runs in one track and why don't you just use a bunch of existing GPX files without merging them first? GPX Animator is capable to render one animation with dozen of GPX files at the same time.

**Comment by willjobs** [comment] 2021-01-26 15:44
For context, here's what I'm going for: https://www.reddit.com/r/dataisbeautiful/comments/kztniz/oc_time_lapse_of_running_every_street_of_salt/. 

The main issue I found is that, when using multiple GPX files that have different dates, even without merging, there's some issue where the file that is created seems to have a very small number of frames (possibly only one?) that is white with the OpenStreetMap and GPX animator titles. This seems fixed if I specify a forced point time interval of, e.g., 1000 milliseconds. However, the problem then is what do when you have dozens/hundreds of GPX files, and they all need to specify a forced point time interval. Is there a way to specify the same forced point time interval for all tracks at once?

Here is an example using 4 GPX files that are within the same town, but that visit distant unconnected parts of the map. The GPX files I used to make these are attached to this post: [gpx_files.zip](https://github.com/zdila/gpx-animator/files/5874234/gpx_files.zip).

1. If I use the GPX files as-is, with 4 separate "tracks" in the GPX Animator UI, I get a 4 KB MP4 with just a white background and the GPX animator + OpenStreetMap names: https://i.imgur.com/zKXl7oV.mp4

2. If I do the same as #&#x2060;1, but set each track to have a forced point time interval of 1000ms, I get this: https://i.imgur.com/Ub3nHh4.mp4. Much better.

Since I have over 200 GPX files, I tried to merge them. I followed the guide from the reddit post I mentioned above, merging all my GPX files into a single file. I tried both (1) https://joewein.net/bike/gpxmerge/, which the original post mentions, and that puts each GPX files into its own track segment (`<trkseg>`); and (2) https://gotoes.org/strava/Combine_GPX_TCX_FIT_Files.php, which combines all data points into a single track (`<trk>`). The merged files are attached: [merged_gpx_files.zip](https://github.com/zdila/gpx-animator/files/5874312/merged_gpx_files.zip).

3a. If I use the [Joe Wein site](https://joewein.net/bike/gpxmerge/), I get this: https://i.imgur.com/mIcrsEq.mp4. Another 4 KB white-screen video.

3b. If I do the same as 3a, but include the forced point time interval of 1000 ms, I get this: https://i.imgur.com/61o2Yzw.mp4. The same as #&#x2060;2 above.

4a. If I use the [gotoes site](https://gotoes.org/strava/Combine_GPX_TCX_FIT_Files.php) to make the merged GPX, I get this: https://i.imgur.com/ZnSv0jY.mp4. There are two issues with this. One is it draws the routes with a significant time delay between each, which makes sense because the GPX files are from different dates, but it's not what I want. And also, it connects points from different routes, which also makes sense, because each point is considered "next to" the point that came before and after in the track created by gotoes. But that's not what I want.

4b. If I use the same gotoes merged file in 4a, but use a forced point time interval of 1000 ms, I get this: https://i.imgur.com/M7fVPAf.mp4. So, the time issue is fixed, but disconnected routes are still connected (which is to be expected).

So, it seems like what I want is either #&#x2060;2 or #&#x2060;3b. The issue with #&#x2060;2 (using each GPX file separately, specifying a forced point time interval for each) is that I have over 200 files, and specifying each one, and its associated forced point time interval of 1000ms, is very time-consuming, both at the command line and in the GUI. Is there a way to specify a whole folder of files, and single common forced point time interval for all GPX files?

The issue with #&#x2060;3b is that the Joe Wein site only accepts 5 files at a time. I can write a Python script to do what his site does, but I'd rather not if I don't have to.

---

As a side note for anyone who reads this in the future: my runs were captured using Nike Run Club. In order to get GPX files, I used https://nexporter.bullrox.net/, from which you can download the GPX files and sync to Strava. Alternatively, you could use the iOS app RunGap, but you'd have to do that one run at a time, which is tedious on a phone.

**Comment by McPringle** [comment] 2021-01-27 19:02
Thank you very much for your explanation. I'll go through it bit by bit... :-)

To your 1: If I use the 4 provided GPX files with GPX Animator without changing the standard settings I get a working movie file "test-1,mp4". Then I just set the speedup to 5'000 (makes it play faster) and removed the flashback duration (now empty = no white flash between the tracks). Both settings are on the general tab and are valid for the whole animation. The result was "test-2.mp4". Next, I just set the speedup to 10'000 and got "test-3.mp4". For me it just worked out of the box. I did all tests with version 1.6, which is available since round about two weeks. Which version did you use? Which OS are you running?

All files are available here (for 30 days):
https://mcpringle.duckdns.org/nextcloud/s/HNYCqkZmJ7jmZS8

**Comment by McPringle** [comment] 2021-01-27 19:16
To your 3a: That worked for me. To make the animation nicer, I removed the flashback duration and set the speedup to 8'000. The result is "joewein.mp4". I published the files in the same directory for you to review.

**Comment by McPringle** [comment] 2021-01-27 21:18
To your 4a: I can reproduce your problem here. This behaviour is related to the GPX file and the track sections. The file "merged_joewein.gpx" contains multiple track segments, one per run. The pause between these segments is skipped. The file "merged_gotoes.gpx" contains only one track segment. No pause, that could be skipped.

**Comment by willjobs** [comment] 2021-01-27 21:37
Thank you so much for your time and the amount of work you're putting into this! :)

I'm on Windows 10, using GPX Animator version 1.6.0. I just realized the one big thing I didn't mention is that I've been setting Total Time, instead of using Speedup. In the examples I listed above, I set Total Time to 8 seconds. I think that is the key difference between my results and yours. For example, I'm able to replicate your test-1.mp4 if I leave the settings as-is, but I get [my version](https://i.imgur.com/zKXl7oV.mp4), a 4 KB video of just a white screen, after setting the Total Time to 8 seconds.

Also, one thing I just noticed (but forgot to mention) is that in my [second example](https://i.imgur.com/Ub3nHh4.mp4), all the tracks start at the same time, which is fine for my purposes, but is different than what I expected. I think that's just because I used Forced Point Time Interval to avoid the jumps in time.

**Comment by willjobs** [comment] 2021-01-27 21:40
So I guess there are a couple questions remaining:

1. Why does setting Total Time act the way I'm observing, e.g., for example 1, making a 4 KB video < 1 second long?
2. If I do end up needing to use Forced Point Time Interval, is there a way to specify that setting for many videos in one place? Or a way to tell the command line to load all the GPX files in a folder and specify the Forced Point Time Interval for each?

Thanks again!

**Comment by McPringle** [comment] 2021-01-28 13:33
This issue here contains several bugs in addition to the idea of a new feature. I will split this issue and create a separate issue for each bug. This will make it easier for me to keep track since GPX Animator is just a spare time project.

**Comment by willjobs** [comment] 2021-01-28 19:38
Thanks so much for your help! Feel free to close out this issue if you don't need it for tracking.

**Comment by McPringle** [comment] 2021-01-30 16:51
@willjobs asked:

>If I do end up needing to use Forced Point Time Interval, is there a way to specify that setting for many videos in one place? Or a way to tell the command line to load all the GPX files in a folder and specify the Forced Point Time Interval for each?

GPX Animator has no support for wildcards on the command line yet. I added an issue for this feature: #319 

As of today, there is no way to specify a _forced point time interval_ for all loaded files at once.

**Comment by McPringle** [comment] 2021-01-30 16:56
This issue here contains several bugs in addition to the idea of a new feature. I have split this issue into #317, #318, and #319. This issue here will now be closed. If you are interested, subscribe to the other issues to get notifications (on the right side of each issue):

![image](https://user-images.githubusercontent.com/1254039/106362678-6c302880-6324-11eb-991e-1370b5d074e3.png)

**Closed by McPringle** 2021-01-30 16:56 UTC
Labels: analyze
